// GENERATED FILE — do not edit by hand.
// Regenerate with: node scripts/generate-content-schema.mjs
// Source of truth for the key list is the TRANSLATIONS object in index.html.

import {defineType, defineField} from 'sanity'

export const siteContent = defineType({
  name: 'siteContent',
  title: 'Page text',
  type: 'document',
  groups: [
    {name: 'meta', title: 'Meta & SEO'},
    {name: 'nav', title: 'Navigation'},
    {name: 'hero', title: 'Hero'},
    {name: 'trust', title: 'Trust strip'},
    {name: 'about', title: 'About Govind'},
    {name: 'journeys', title: 'Journeys'},
    {name: 'tour', title: 'Individual tours'},
    {name: 'wellness', title: 'Ayurveda & wellness'},
    {name: 'why', title: 'Why Govind'},
    {name: 'gallery', title: 'Gallery'},
    {name: 'reviews', title: 'Reviews'},
    {name: 'info', title: 'Travel info'},
    {name: 'enquiry', title: 'Enquiry'},
    {name: 'form', title: 'Enquiry form'},
    {name: 'footer', title: 'Footer'},
    {name: 'whatsapp', title: 'WhatsApp'},
  ],
  fields: [
    defineField({
      name: 'meta_title',
      title: 'title',
      description: 'meta.title',
      type: 'localeString',
      group: 'meta',
    }),
    defineField({
      name: 'meta_description',
      title: 'description',
      description: 'meta.description',
      type: 'localeText',
      group: 'meta',
    }),
    defineField({
      name: 'meta_ogDescription',
      title: 'ogDescription',
      description: 'meta.ogDescription',
      type: 'localeString',
      group: 'meta',
    }),
    defineField({
      name: 'nav_aria',
      title: 'aria',
      description: 'nav.aria',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_home',
      title: 'home',
      description: 'nav.home',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_language',
      title: 'language',
      description: 'nav.language',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_menu',
      title: 'menu',
      description: 'nav.menu',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_cta',
      title: 'cta',
      description: 'nav.cta',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_about',
      title: 'about',
      description: 'nav.about',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_journeys',
      title: 'journeys',
      description: 'nav.journeys',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_wellness',
      title: 'wellness',
      description: 'nav.wellness',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_gallery',
      title: 'gallery',
      description: 'nav.gallery',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_info',
      title: 'info',
      description: 'nav.info',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_reviews',
      title: 'reviews',
      description: 'nav.reviews',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_contact',
      title: 'contact',
      description: 'nav.contact',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'hero_eyebrow',
      title: 'eyebrow',
      description: 'hero.eyebrow',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'hero_title',
      title: 'title',
      description: 'hero.title',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'hero_lede',
      title: 'lede',
      description: 'hero.lede',
      type: 'localeText',
      group: 'hero',
    }),
    defineField({
      name: 'hero_cta',
      title: 'cta',
      description: 'hero.cta',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'hero_alt',
      title: 'alt',
      description: 'hero.alt',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'trust_aria',
      title: 'aria',
      description: 'trust.aria',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_1_figure',
      title: '1 · figure',
      description: 'trust.1.figure',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_1_label',
      title: '1 · label',
      description: 'trust.1.label',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_2_figure',
      title: '2 · figure',
      description: 'trust.2.figure',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_2_label',
      title: '2 · label',
      description: 'trust.2.label',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_3_figure',
      title: '3 · figure',
      description: 'trust.3.figure',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_3_label',
      title: '3 · label',
      description: 'trust.3.label',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_4_figure',
      title: '4 · figure',
      description: 'trust.4.figure',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_4_label',
      title: '4 · label',
      description: 'trust.4.label',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'about_eyebrow',
      title: 'eyebrow',
      description: 'about.eyebrow',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_title',
      title: 'title',
      description: 'about.title',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_alt',
      title: 'alt',
      description: 'about.alt',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_p1',
      title: 'p1',
      description: 'about.p1',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_p2',
      title: 'p2',
      description: 'about.p2',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_p3',
      title: 'p3',
      description: 'about.p3',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_p4',
      title: 'p4',
      description: 'about.p4',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_p5',
      title: 'p5',
      description: 'about.p5',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_p6',
      title: 'p6',
      description: 'about.p6',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_quote',
      title: 'quote',
      description: 'about.quote',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_credentialsAria',
      title: 'credentialsAria',
      description: 'about.credentialsAria',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_cred1',
      title: 'cred1',
      description: 'about.cred1',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_cred2',
      title: 'cred2',
      description: 'about.cred2',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_cred3',
      title: 'cred3',
      description: 'about.cred3',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_cred4',
      title: 'cred4',
      description: 'about.cred4',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'journeys_eyebrow',
      title: 'eyebrow',
      description: 'journeys.eyebrow',
      type: 'localeString',
      group: 'journeys',
    }),
    defineField({
      name: 'journeys_title',
      title: 'title',
      description: 'journeys.title',
      type: 'localeString',
      group: 'journeys',
    }),
    defineField({
      name: 'journeys_lede',
      title: 'lede',
      description: 'journeys.lede',
      type: 'localeString',
      group: 'journeys',
    }),
    defineField({
      name: 'tour_cta',
      title: 'cta',
      description: 'tour.cta',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_close',
      title: 'close',
      description: 'tour.close',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_factsLabel',
      title: 'factsLabel',
      description: 'tour.factsLabel',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_bestLabel',
      title: 'bestLabel',
      description: 'tour.bestLabel',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_enquire',
      title: 'enquire',
      description: 'tour.enquire',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_title',
      title: 'goldenTriangle · title',
      description: 'tour.goldenTriangle.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_text',
      title: 'goldenTriangle · text',
      description: 'tour.goldenTriangle.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_alt',
      title: 'goldenTriangle · alt',
      description: 'tour.goldenTriangle.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_lede',
      title: 'goldenTriangle · lede',
      description: 'tour.goldenTriangle.lede',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_fact1',
      title: 'goldenTriangle · fact1',
      description: 'tour.goldenTriangle.fact1',
      type: 'localeText',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_fact2',
      title: 'goldenTriangle · fact2',
      description: 'tour.goldenTriangle.fact2',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_fact3',
      title: 'goldenTriangle · fact3',
      description: 'tour.goldenTriangle.fact3',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_fact4',
      title: 'goldenTriangle · fact4',
      description: 'tour.goldenTriangle.fact4',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_best',
      title: 'goldenTriangle · best',
      description: 'tour.goldenTriangle.best',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_title',
      title: 'rajasthan · title',
      description: 'tour.rajasthan.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_text',
      title: 'rajasthan · text',
      description: 'tour.rajasthan.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_alt',
      title: 'rajasthan · alt',
      description: 'tour.rajasthan.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_lede',
      title: 'rajasthan · lede',
      description: 'tour.rajasthan.lede',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_fact1',
      title: 'rajasthan · fact1',
      description: 'tour.rajasthan.fact1',
      type: 'localeText',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_fact2',
      title: 'rajasthan · fact2',
      description: 'tour.rajasthan.fact2',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_fact3',
      title: 'rajasthan · fact3',
      description: 'tour.rajasthan.fact3',
      type: 'localeText',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_fact4',
      title: 'rajasthan · fact4',
      description: 'tour.rajasthan.fact4',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_best',
      title: 'rajasthan · best',
      description: 'tour.rajasthan.best',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ranthambore_title',
      title: 'ranthambore · title',
      description: 'tour.ranthambore.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ranthambore_text',
      title: 'ranthambore · text',
      description: 'tour.ranthambore.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ranthambore_alt',
      title: 'ranthambore · alt',
      description: 'tour.ranthambore.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ranthambore_lede',
      title: 'ranthambore · lede',
      description: 'tour.ranthambore.lede',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ranthambore_fact1',
      title: 'ranthambore · fact1',
      description: 'tour.ranthambore.fact1',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ranthambore_fact2',
      title: 'ranthambore · fact2',
      description: 'tour.ranthambore.fact2',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ranthambore_fact3',
      title: 'ranthambore · fact3',
      description: 'tour.ranthambore.fact3',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ranthambore_fact4',
      title: 'ranthambore · fact4',
      description: 'tour.ranthambore.fact4',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ranthambore_best',
      title: 'ranthambore · best',
      description: 'tour.ranthambore.best',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_title',
      title: 'kerala · title',
      description: 'tour.kerala.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_text',
      title: 'kerala · text',
      description: 'tour.kerala.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_alt',
      title: 'kerala · alt',
      description: 'tour.kerala.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_lede',
      title: 'kerala · lede',
      description: 'tour.kerala.lede',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_fact1',
      title: 'kerala · fact1',
      description: 'tour.kerala.fact1',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_fact2',
      title: 'kerala · fact2',
      description: 'tour.kerala.fact2',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_fact3',
      title: 'kerala · fact3',
      description: 'tour.kerala.fact3',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_fact4',
      title: 'kerala · fact4',
      description: 'tour.kerala.fact4',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_best',
      title: 'kerala · best',
      description: 'tour.kerala.best',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_title',
      title: 'ladakh · title',
      description: 'tour.ladakh.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_text',
      title: 'ladakh · text',
      description: 'tour.ladakh.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_alt',
      title: 'ladakh · alt',
      description: 'tour.ladakh.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_lede',
      title: 'ladakh · lede',
      description: 'tour.ladakh.lede',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_fact1',
      title: 'ladakh · fact1',
      description: 'tour.ladakh.fact1',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_fact2',
      title: 'ladakh · fact2',
      description: 'tour.ladakh.fact2',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_fact3',
      title: 'ladakh · fact3',
      description: 'tour.ladakh.fact3',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_fact4',
      title: 'ladakh · fact4',
      description: 'tour.ladakh.fact4',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_best',
      title: 'ladakh · best',
      description: 'tour.ladakh.best',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_title',
      title: 'varanasi · title',
      description: 'tour.varanasi.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_text',
      title: 'varanasi · text',
      description: 'tour.varanasi.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_alt',
      title: 'varanasi · alt',
      description: 'tour.varanasi.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_lede',
      title: 'varanasi · lede',
      description: 'tour.varanasi.lede',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_fact1',
      title: 'varanasi · fact1',
      description: 'tour.varanasi.fact1',
      type: 'localeText',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_fact2',
      title: 'varanasi · fact2',
      description: 'tour.varanasi.fact2',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_fact3',
      title: 'varanasi · fact3',
      description: 'tour.varanasi.fact3',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_fact4',
      title: 'varanasi · fact4',
      description: 'tour.varanasi.fact4',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_best',
      title: 'varanasi · best',
      description: 'tour.varanasi.best',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_title',
      title: 'southIndia · title',
      description: 'tour.southIndia.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_text',
      title: 'southIndia · text',
      description: 'tour.southIndia.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_alt',
      title: 'southIndia · alt',
      description: 'tour.southIndia.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_lede',
      title: 'southIndia · lede',
      description: 'tour.southIndia.lede',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_fact1',
      title: 'southIndia · fact1',
      description: 'tour.southIndia.fact1',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_fact2',
      title: 'southIndia · fact2',
      description: 'tour.southIndia.fact2',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_fact3',
      title: 'southIndia · fact3',
      description: 'tour.southIndia.fact3',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_fact4',
      title: 'southIndia · fact4',
      description: 'tour.southIndia.fact4',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_best',
      title: 'southIndia · best',
      description: 'tour.southIndia.best',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'wellness_eyebrow',
      title: 'eyebrow',
      description: 'wellness.eyebrow',
      type: 'localeString',
      group: 'wellness',
    }),
    defineField({
      name: 'wellness_title',
      title: 'title',
      description: 'wellness.title',
      type: 'localeString',
      group: 'wellness',
    }),
    defineField({
      name: 'wellness_alt',
      title: 'alt',
      description: 'wellness.alt',
      type: 'localeString',
      group: 'wellness',
    }),
    defineField({
      name: 'wellness_p1',
      title: 'p1',
      description: 'wellness.p1',
      type: 'localeText',
      group: 'wellness',
    }),
    defineField({
      name: 'wellness_p2',
      title: 'p2',
      description: 'wellness.p2',
      type: 'localeText',
      group: 'wellness',
    }),
    defineField({
      name: 'wellness_listAria',
      title: 'listAria',
      description: 'wellness.listAria',
      type: 'localeString',
      group: 'wellness',
    }),
    defineField({
      name: 'wellness_item1',
      title: 'item1',
      description: 'wellness.item1',
      type: 'localeString',
      group: 'wellness',
    }),
    defineField({
      name: 'wellness_item2',
      title: 'item2',
      description: 'wellness.item2',
      type: 'localeString',
      group: 'wellness',
    }),
    defineField({
      name: 'wellness_item3',
      title: 'item3',
      description: 'wellness.item3',
      type: 'localeString',
      group: 'wellness',
    }),
    defineField({
      name: 'wellness_item4',
      title: 'item4',
      description: 'wellness.item4',
      type: 'localeString',
      group: 'wellness',
    }),
    defineField({
      name: 'wellness_cta',
      title: 'cta',
      description: 'wellness.cta',
      type: 'localeString',
      group: 'wellness',
    }),
    defineField({
      name: 'why_eyebrow',
      title: 'eyebrow',
      description: 'why.eyebrow',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_title',
      title: 'title',
      description: 'why.title',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_lede',
      title: 'lede',
      description: 'why.lede',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_1_title',
      title: '1 · title',
      description: 'why.1.title',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_1_text',
      title: '1 · text',
      description: 'why.1.text',
      type: 'localeText',
      group: 'why',
    }),
    defineField({
      name: 'why_2_title',
      title: '2 · title',
      description: 'why.2.title',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_2_text',
      title: '2 · text',
      description: 'why.2.text',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_3_title',
      title: '3 · title',
      description: 'why.3.title',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_3_text',
      title: '3 · text',
      description: 'why.3.text',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_4_title',
      title: '4 · title',
      description: 'why.4.title',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_4_text',
      title: '4 · text',
      description: 'why.4.text',
      type: 'localeText',
      group: 'why',
    }),
    defineField({
      name: 'gallery_eyebrow',
      title: 'eyebrow',
      description: 'gallery.eyebrow',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_title',
      title: 'title',
      description: 'gallery.title',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_lede',
      title: 'lede',
      description: 'gallery.lede',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_amber',
      title: 'amber',
      description: 'gallery.amber',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_taj',
      title: 'taj',
      description: 'gallery.taj',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_gopuram',
      title: 'gopuram',
      description: 'gallery.gopuram',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_gwalior',
      title: 'gwalior',
      description: 'gallery.gwalior',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_darasuram',
      title: 'darasuram',
      description: 'gallery.darasuram',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_khajuraho',
      title: 'khajuraho',
      description: 'gallery.khajuraho',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_srirangam',
      title: 'srirangam',
      description: 'gallery.srirangam',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_shiva',
      title: 'shiva',
      description: 'gallery.shiva',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_mahabalipuram',
      title: 'mahabalipuram',
      description: 'gallery.mahabalipuram',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_qutub',
      title: 'qutub',
      description: 'gallery.qutub',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_govindGuest',
      title: 'govindGuest',
      description: 'gallery.govindGuest',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_hawaMahal',
      title: 'hawaMahal',
      description: 'gallery.hawaMahal',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_goldenTemple',
      title: 'goldenTemple',
      description: 'gallery.goldenTemple',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_tajGate',
      title: 'tajGate',
      description: 'gallery.tajGate',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_jaisalmerLane',
      title: 'jaisalmerLane',
      description: 'gallery.jaisalmerLane',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_tiger',
      title: 'tiger',
      description: 'gallery.tiger',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_rajasthani',
      title: 'rajasthani',
      description: 'gallery.rajasthani',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_fatehpur',
      title: 'fatehpur',
      description: 'gallery.fatehpur',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_amberShow',
      title: 'amberShow',
      description: 'gallery.amberShow',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_indiaGate',
      title: 'indiaGate',
      description: 'gallery.indiaGate',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'reviews_eyebrow',
      title: 'eyebrow',
      description: 'reviews.eyebrow',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_title',
      title: 'title',
      description: 'reviews.title',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_videoEyebrow',
      title: 'videoEyebrow',
      description: 'reviews.videoEyebrow',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_videoTitle',
      title: 'videoTitle',
      description: 'reviews.videoTitle',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_videoText',
      title: 'videoText',
      description: 'reviews.videoText',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_videoAria',
      title: 'videoAria',
      description: 'reviews.videoAria',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_videoFallback',
      title: 'videoFallback',
      description: 'reviews.videoFallback',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_1_quote',
      title: '1 · quote',
      description: 'reviews.1.quote',
      type: 'localeText',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_1_author',
      title: '1 · author',
      description: 'reviews.1.author',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_2_quote',
      title: '2 · quote',
      description: 'reviews.2.quote',
      type: 'localeText',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_2_author',
      title: '2 · author',
      description: 'reviews.2.author',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_3_quote',
      title: '3 · quote',
      description: 'reviews.3.quote',
      type: 'localeText',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_3_author',
      title: '3 · author',
      description: 'reviews.3.author',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formTitle',
      title: 'formTitle',
      description: 'reviews.formTitle',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formLede',
      title: 'formLede',
      description: 'reviews.formLede',
      type: 'localeText',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formName',
      title: 'formName',
      description: 'reviews.formName',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formCity',
      title: 'formCity',
      description: 'reviews.formCity',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formRating',
      title: 'formRating',
      description: 'reviews.formRating',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_star1',
      title: 'star1',
      description: 'reviews.star1',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_star2',
      title: 'star2',
      description: 'reviews.star2',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_star3',
      title: 'star3',
      description: 'reviews.star3',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_star4',
      title: 'star4',
      description: 'reviews.star4',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_star5',
      title: 'star5',
      description: 'reviews.star5',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formText',
      title: 'formText',
      description: 'reviews.formText',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formTextPlaceholder',
      title: 'formTextPlaceholder',
      description: 'reviews.formTextPlaceholder',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formConsent',
      title: 'formConsent',
      description: 'reviews.formConsent',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formSubmit',
      title: 'formSubmit',
      description: 'reviews.formSubmit',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formSending',
      title: 'formSending',
      description: 'reviews.formSending',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formSuccess',
      title: 'formSuccess',
      description: 'reviews.formSuccess',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_formError',
      title: 'formError',
      description: 'reviews.formError',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'info_eyebrow',
      title: 'eyebrow',
      description: 'info.eyebrow',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_title',
      title: 'title',
      description: 'info.title',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_lede',
      title: 'lede',
      description: 'info.lede',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'info_aria',
      title: 'aria',
      description: 'info.aria',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_visa',
      title: 'visa',
      description: 'info.visa',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_visa_text',
      title: 'visa · text',
      description: 'info.visa.text',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'info_season',
      title: 'season',
      description: 'info.season',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_season_text',
      title: 'season · text',
      description: 'info.season.text',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'info_health',
      title: 'health',
      description: 'info.health',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_health_text',
      title: 'health · text',
      description: 'info.health.text',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'info_safety',
      title: 'safety',
      description: 'info.safety',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_safety_text',
      title: 'safety · text',
      description: 'info.safety.text',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'info_cta',
      title: 'cta',
      description: 'info.cta',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_note',
      title: 'note',
      description: 'info.note',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'enquiry_eyebrow',
      title: 'eyebrow',
      description: 'enquiry.eyebrow',
      type: 'localeString',
      group: 'enquiry',
    }),
    defineField({
      name: 'enquiry_title',
      title: 'title',
      description: 'enquiry.title',
      type: 'localeString',
      group: 'enquiry',
    }),
    defineField({
      name: 'enquiry_lede',
      title: 'lede',
      description: 'enquiry.lede',
      type: 'localeString',
      group: 'enquiry',
    }),
    defineField({
      name: 'form_name',
      title: 'name',
      description: 'form.name',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_email',
      title: 'email',
      description: 'form.email',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_phone',
      title: 'phone',
      description: 'form.phone',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_phonePlaceholder',
      title: 'phonePlaceholder',
      description: 'form.phonePlaceholder',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_dateFrom',
      title: 'dateFrom',
      description: 'form.dateFrom',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_dateTo',
      title: 'dateTo',
      description: 'form.dateTo',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_people',
      title: 'people',
      description: 'form.people',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_interests',
      title: 'interests',
      description: 'form.interests',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_interestsPlaceholder',
      title: 'interestsPlaceholder',
      description: 'form.interestsPlaceholder',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_message',
      title: 'message',
      description: 'form.message',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_messagePlaceholder',
      title: 'messagePlaceholder',
      description: 'form.messagePlaceholder',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_consent',
      title: 'consent',
      description: 'form.consent',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_submit',
      title: 'submit',
      description: 'form.submit',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_sending',
      title: 'sending',
      description: 'form.sending',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_success',
      title: 'success',
      description: 'form.success',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_error',
      title: 'error',
      description: 'form.error',
      type: 'localeText',
      group: 'form',
    }),
    defineField({
      name: 'footer_note',
      title: 'note',
      description: 'footer.note',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_response',
      title: 'response',
      description: 'footer.response',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_contactAria',
      title: 'contactAria',
      description: 'footer.contactAria',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_phone',
      title: 'phone',
      description: 'footer.phone',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_email',
      title: 'email',
      description: 'footer.email',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_whatsapp',
      title: 'whatsapp',
      description: 'footer.whatsapp',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_legalAria',
      title: 'legalAria',
      description: 'footer.legalAria',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_privacy',
      title: 'privacy',
      description: 'footer.privacy',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_imprint',
      title: 'imprint',
      description: 'footer.imprint',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_terms',
      title: 'terms',
      description: 'footer.terms',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'whatsapp_label',
      title: 'label',
      description: 'whatsapp.label',
      type: 'localeString',
      group: 'whatsapp',
    }),
    defineField({
      name: 'whatsapp_aria',
      title: 'aria',
      description: 'whatsapp.aria',
      type: 'localeString',
      group: 'whatsapp',
    }),
    defineField({
      name: 'whatsapp_url',
      title: 'url',
      description: 'whatsapp.url',
      type: 'localeText',
      group: 'whatsapp',
    }),
  ],
  preview: {
    prepare: () => ({title: 'Page text'}),
  },
})
