// GENERATED FILE — do not edit by hand.
// Regenerate with: node scripts/generate-content-schema.mjs
// Source of truth for the key list is the TRANSLATIONS object in index.html.

import {defineType, defineField} from 'sanity'

export const siteContent = defineType({
  name: 'siteContent',
  title: 'Seitentexte',
  type: 'document',
  groups: [
    {name: 'meta', title: 'Meta & SEO'},
    {name: 'nav', title: 'Navigation'},
    {name: 'hero', title: 'Startbereich'},
    {name: 'trust', title: 'Vertrauensleiste'},
    {name: 'about', title: 'Über Govind'},
    {name: 'journeys', title: 'Reisen'},
    {name: 'tour', title: 'Einzelne Reisen'},
    {name: 'why', title: 'Warum Govind'},
    {name: 'gallery', title: 'Impressionen'},
    {name: 'reviews', title: 'Bewertungen'},
    {name: 'info', title: 'Reiseinfos'},
    {name: 'enquiry', title: 'Anfrage'},
    {name: 'form', title: 'Formular'},
    {name: 'footer', title: 'Fußzeile'},
    {name: 'whatsapp', title: 'WhatsApp'},
  ],
  fields: [
    defineField({
      name: 'meta_title',
      title: 'title',
      description: 'meta.title',
      type: 'localeString',
      group: 'meta',
    }),
    defineField({
      name: 'meta_description',
      title: 'description',
      description: 'meta.description',
      type: 'localeText',
      group: 'meta',
    }),
    defineField({
      name: 'meta_ogDescription',
      title: 'ogDescription',
      description: 'meta.ogDescription',
      type: 'localeString',
      group: 'meta',
    }),
    defineField({
      name: 'nav_aria',
      title: 'aria',
      description: 'nav.aria',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_home',
      title: 'home',
      description: 'nav.home',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_language',
      title: 'language',
      description: 'nav.language',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_menu',
      title: 'menu',
      description: 'nav.menu',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_cta',
      title: 'cta',
      description: 'nav.cta',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_about',
      title: 'about',
      description: 'nav.about',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_journeys',
      title: 'journeys',
      description: 'nav.journeys',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_gallery',
      title: 'gallery',
      description: 'nav.gallery',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_info',
      title: 'info',
      description: 'nav.info',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_reviews',
      title: 'reviews',
      description: 'nav.reviews',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'nav_contact',
      title: 'contact',
      description: 'nav.contact',
      type: 'localeString',
      group: 'nav',
    }),
    defineField({
      name: 'hero_eyebrow',
      title: 'eyebrow',
      description: 'hero.eyebrow',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'hero_title',
      title: 'title',
      description: 'hero.title',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'hero_lede',
      title: 'lede',
      description: 'hero.lede',
      type: 'localeText',
      group: 'hero',
    }),
    defineField({
      name: 'hero_cta',
      title: 'cta',
      description: 'hero.cta',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'hero_alt',
      title: 'alt',
      description: 'hero.alt',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'trust_aria',
      title: 'aria',
      description: 'trust.aria',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_1_figure',
      title: '1 · figure',
      description: 'trust.1.figure',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_1_label',
      title: '1 · label',
      description: 'trust.1.label',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_2_figure',
      title: '2 · figure',
      description: 'trust.2.figure',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_2_label',
      title: '2 · label',
      description: 'trust.2.label',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_3_figure',
      title: '3 · figure',
      description: 'trust.3.figure',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_3_label',
      title: '3 · label',
      description: 'trust.3.label',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_4_figure',
      title: '4 · figure',
      description: 'trust.4.figure',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'trust_4_label',
      title: '4 · label',
      description: 'trust.4.label',
      type: 'localeString',
      group: 'trust',
    }),
    defineField({
      name: 'about_eyebrow',
      title: 'eyebrow',
      description: 'about.eyebrow',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_title',
      title: 'title',
      description: 'about.title',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_alt',
      title: 'alt',
      description: 'about.alt',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_p1',
      title: 'p1',
      description: 'about.p1',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_p2',
      title: 'p2',
      description: 'about.p2',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_p3',
      title: 'p3',
      description: 'about.p3',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_p4',
      title: 'p4',
      description: 'about.p4',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_p5',
      title: 'p5',
      description: 'about.p5',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_p6',
      title: 'p6',
      description: 'about.p6',
      type: 'localeText',
      group: 'about',
    }),
    defineField({
      name: 'about_quote',
      title: 'quote',
      description: 'about.quote',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_credentialsAria',
      title: 'credentialsAria',
      description: 'about.credentialsAria',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_cred1',
      title: 'cred1',
      description: 'about.cred1',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_cred2',
      title: 'cred2',
      description: 'about.cred2',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_cred3',
      title: 'cred3',
      description: 'about.cred3',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'about_cred4',
      title: 'cred4',
      description: 'about.cred4',
      type: 'localeString',
      group: 'about',
    }),
    defineField({
      name: 'journeys_eyebrow',
      title: 'eyebrow',
      description: 'journeys.eyebrow',
      type: 'localeString',
      group: 'journeys',
    }),
    defineField({
      name: 'journeys_title',
      title: 'title',
      description: 'journeys.title',
      type: 'localeString',
      group: 'journeys',
    }),
    defineField({
      name: 'journeys_lede',
      title: 'lede',
      description: 'journeys.lede',
      type: 'localeString',
      group: 'journeys',
    }),
    defineField({
      name: 'tour_cta',
      title: 'cta',
      description: 'tour.cta',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_title',
      title: 'goldenTriangle · title',
      description: 'tour.goldenTriangle.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_text',
      title: 'goldenTriangle · text',
      description: 'tour.goldenTriangle.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_goldenTriangle_alt',
      title: 'goldenTriangle · alt',
      description: 'tour.goldenTriangle.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_title',
      title: 'rajasthan · title',
      description: 'tour.rajasthan.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_text',
      title: 'rajasthan · text',
      description: 'tour.rajasthan.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_rajasthan_alt',
      title: 'rajasthan · alt',
      description: 'tour.rajasthan.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_title',
      title: 'kerala · title',
      description: 'tour.kerala.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_text',
      title: 'kerala · text',
      description: 'tour.kerala.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_kerala_alt',
      title: 'kerala · alt',
      description: 'tour.kerala.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_title',
      title: 'ladakh · title',
      description: 'tour.ladakh.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_text',
      title: 'ladakh · text',
      description: 'tour.ladakh.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_ladakh_alt',
      title: 'ladakh · alt',
      description: 'tour.ladakh.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_title',
      title: 'varanasi · title',
      description: 'tour.varanasi.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_text',
      title: 'varanasi · text',
      description: 'tour.varanasi.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_varanasi_alt',
      title: 'varanasi · alt',
      description: 'tour.varanasi.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_title',
      title: 'southIndia · title',
      description: 'tour.southIndia.title',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_text',
      title: 'southIndia · text',
      description: 'tour.southIndia.text',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'tour_southIndia_alt',
      title: 'southIndia · alt',
      description: 'tour.southIndia.alt',
      type: 'localeString',
      group: 'tour',
    }),
    defineField({
      name: 'why_eyebrow',
      title: 'eyebrow',
      description: 'why.eyebrow',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_title',
      title: 'title',
      description: 'why.title',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_lede',
      title: 'lede',
      description: 'why.lede',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_1_title',
      title: '1 · title',
      description: 'why.1.title',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_1_text',
      title: '1 · text',
      description: 'why.1.text',
      type: 'localeText',
      group: 'why',
    }),
    defineField({
      name: 'why_2_title',
      title: '2 · title',
      description: 'why.2.title',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_2_text',
      title: '2 · text',
      description: 'why.2.text',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_3_title',
      title: '3 · title',
      description: 'why.3.title',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_3_text',
      title: '3 · text',
      description: 'why.3.text',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_4_title',
      title: '4 · title',
      description: 'why.4.title',
      type: 'localeString',
      group: 'why',
    }),
    defineField({
      name: 'why_4_text',
      title: '4 · text',
      description: 'why.4.text',
      type: 'localeText',
      group: 'why',
    }),
    defineField({
      name: 'gallery_eyebrow',
      title: 'eyebrow',
      description: 'gallery.eyebrow',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_title',
      title: 'title',
      description: 'gallery.title',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_lede',
      title: 'lede',
      description: 'gallery.lede',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_amber',
      title: 'amber',
      description: 'gallery.amber',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_taj',
      title: 'taj',
      description: 'gallery.taj',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_gopuram',
      title: 'gopuram',
      description: 'gallery.gopuram',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_gwalior',
      title: 'gwalior',
      description: 'gallery.gwalior',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_darasuram',
      title: 'darasuram',
      description: 'gallery.darasuram',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_khajuraho',
      title: 'khajuraho',
      description: 'gallery.khajuraho',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_srirangam',
      title: 'srirangam',
      description: 'gallery.srirangam',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_shiva',
      title: 'shiva',
      description: 'gallery.shiva',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_mahabalipuram',
      title: 'mahabalipuram',
      description: 'gallery.mahabalipuram',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'gallery_qutub',
      title: 'qutub',
      description: 'gallery.qutub',
      type: 'localeString',
      group: 'gallery',
    }),
    defineField({
      name: 'reviews_eyebrow',
      title: 'eyebrow',
      description: 'reviews.eyebrow',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_title',
      title: 'title',
      description: 'reviews.title',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_videoEyebrow',
      title: 'videoEyebrow',
      description: 'reviews.videoEyebrow',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_videoTitle',
      title: 'videoTitle',
      description: 'reviews.videoTitle',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_videoText',
      title: 'videoText',
      description: 'reviews.videoText',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_videoAria',
      title: 'videoAria',
      description: 'reviews.videoAria',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_videoFallback',
      title: 'videoFallback',
      description: 'reviews.videoFallback',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_1_quote',
      title: '1 · quote',
      description: 'reviews.1.quote',
      type: 'localeText',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_1_author',
      title: '1 · author',
      description: 'reviews.1.author',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_2_quote',
      title: '2 · quote',
      description: 'reviews.2.quote',
      type: 'localeText',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_2_author',
      title: '2 · author',
      description: 'reviews.2.author',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_3_quote',
      title: '3 · quote',
      description: 'reviews.3.quote',
      type: 'localeText',
      group: 'reviews',
    }),
    defineField({
      name: 'reviews_3_author',
      title: '3 · author',
      description: 'reviews.3.author',
      type: 'localeString',
      group: 'reviews',
    }),
    defineField({
      name: 'info_eyebrow',
      title: 'eyebrow',
      description: 'info.eyebrow',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_title',
      title: 'title',
      description: 'info.title',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_lede',
      title: 'lede',
      description: 'info.lede',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'info_aria',
      title: 'aria',
      description: 'info.aria',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_visa',
      title: 'visa',
      description: 'info.visa',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_visa_text',
      title: 'visa · text',
      description: 'info.visa.text',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'info_season',
      title: 'season',
      description: 'info.season',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_season_text',
      title: 'season · text',
      description: 'info.season.text',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'info_health',
      title: 'health',
      description: 'info.health',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_health_text',
      title: 'health · text',
      description: 'info.health.text',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'info_safety',
      title: 'safety',
      description: 'info.safety',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_safety_text',
      title: 'safety · text',
      description: 'info.safety.text',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'info_cta',
      title: 'cta',
      description: 'info.cta',
      type: 'localeString',
      group: 'info',
    }),
    defineField({
      name: 'info_note',
      title: 'note',
      description: 'info.note',
      type: 'localeText',
      group: 'info',
    }),
    defineField({
      name: 'enquiry_eyebrow',
      title: 'eyebrow',
      description: 'enquiry.eyebrow',
      type: 'localeString',
      group: 'enquiry',
    }),
    defineField({
      name: 'enquiry_title',
      title: 'title',
      description: 'enquiry.title',
      type: 'localeString',
      group: 'enquiry',
    }),
    defineField({
      name: 'enquiry_lede',
      title: 'lede',
      description: 'enquiry.lede',
      type: 'localeString',
      group: 'enquiry',
    }),
    defineField({
      name: 'form_name',
      title: 'name',
      description: 'form.name',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_email',
      title: 'email',
      description: 'form.email',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_phone',
      title: 'phone',
      description: 'form.phone',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_phonePlaceholder',
      title: 'phonePlaceholder',
      description: 'form.phonePlaceholder',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_dateFrom',
      title: 'dateFrom',
      description: 'form.dateFrom',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_dateTo',
      title: 'dateTo',
      description: 'form.dateTo',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_people',
      title: 'people',
      description: 'form.people',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_interests',
      title: 'interests',
      description: 'form.interests',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_interestsPlaceholder',
      title: 'interestsPlaceholder',
      description: 'form.interestsPlaceholder',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_message',
      title: 'message',
      description: 'form.message',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_messagePlaceholder',
      title: 'messagePlaceholder',
      description: 'form.messagePlaceholder',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_consent',
      title: 'consent',
      description: 'form.consent',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_submit',
      title: 'submit',
      description: 'form.submit',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_sending',
      title: 'sending',
      description: 'form.sending',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_success',
      title: 'success',
      description: 'form.success',
      type: 'localeString',
      group: 'form',
    }),
    defineField({
      name: 'form_error',
      title: 'error',
      description: 'form.error',
      type: 'localeText',
      group: 'form',
    }),
    defineField({
      name: 'footer_note',
      title: 'note',
      description: 'footer.note',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_response',
      title: 'response',
      description: 'footer.response',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_contactAria',
      title: 'contactAria',
      description: 'footer.contactAria',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_phone',
      title: 'phone',
      description: 'footer.phone',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_email',
      title: 'email',
      description: 'footer.email',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_whatsapp',
      title: 'whatsapp',
      description: 'footer.whatsapp',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_legalAria',
      title: 'legalAria',
      description: 'footer.legalAria',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_privacy',
      title: 'privacy',
      description: 'footer.privacy',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_imprint',
      title: 'imprint',
      description: 'footer.imprint',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'footer_terms',
      title: 'terms',
      description: 'footer.terms',
      type: 'localeString',
      group: 'footer',
    }),
    defineField({
      name: 'whatsapp_label',
      title: 'label',
      description: 'whatsapp.label',
      type: 'localeString',
      group: 'whatsapp',
    }),
    defineField({
      name: 'whatsapp_aria',
      title: 'aria',
      description: 'whatsapp.aria',
      type: 'localeString',
      group: 'whatsapp',
    }),
    defineField({
      name: 'whatsapp_url',
      title: 'url',
      description: 'whatsapp.url',
      type: 'localeText',
      group: 'whatsapp',
    }),
  ],
  preview: {
    prepare: () => ({title: 'Seitentexte'}),
  },
})
